version: "3.7"
services:
  api:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    restart: always
    depends_on:
      - mq
    networks:
      static-network:
        ipv4_address: 172.29.128.2
  mq:
    image: "rabbitmq:3.7.4-management"
    hostname: "rabbit1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "dev"
    networks:
      static-network:
        ipv4_address: 172.29.128.3
    container_name: "mq"
  front:
    # See https://medium.com/swlh/dockerizing-a-react-application-with-docker-and-nginx-19e88ef8e99a
    container_name: react-dev
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/dev/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    environment:
      - NODE_ENV=development
    networks:
      static-network:
        ipv4_address: 172.29.128.1

networks:
  backend:
    driver: "bridge"
  static-network:
    ipam:
      config:
        - subnet: 172.29.0.0/16